### ISSUE TITLE
error TS2339: Property 'Export' does not exist on type 'typeof NodeFlags'.

### ISSUE THREAD

**Issue by wugelis** [remojansen/TsUML#2]
Hi,

I want to compile it, but i got error follow:

error TS2339: Property 'Export' does not exist on type 'typeof NodeFlags'.

occur in /src/core/parser.ts (108,44)

my npm version is v5.3.0
node version is v8.6.0
tsc version is v2.6.1
tsd version is v0.6.5

thank you very mush.

by Gelis

**Comment by remojansen** [comment]
Hi, sorry but this project is not actively maintained. It was just an experiment done during a hackathon. Feel free to fork it or create your own.

**Comment by wugelis** [comment]
Oh, Regrettably unable to use it!
